Repository MurkSec/BavariaTheGame, pull requests merged in 2018-08, with the labels that each got.

#22 Redwiz666 dev 0.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  BavariaTheGame.py
  README.md
  bavarialogo.PNG
  class_monster.py
  class_player.py
  class_support.py
Labels: bug, enhancement

#33 Gwa2100 dev0.1 graphicengine
  BavariaTheGame.py
  class_graphics.py
  class_monster.py
  class_player.py
  class_support.py
  helper_functions.py
Labels: enhancement

#38 created MEMBERS.md
  MEMBERS.md
Labels: enhancement

#45 added screenwipe function
  helper_functions.py
Labels: bug

#58 Added option to restart if you die.
  BavariaTheGame.py
  class_world.py
Labels: enhancement

#59 modified class_graphics to display the bottom line of graphics
  class_graphics.py
Labels: bug
